---
# tasks file for sbaerlocher.traefik

- name: Create external docker network for traefik
  docker_network:
    name: "{{ traefik_network }}"
    ipam_options:
      subnet: '172.16.1.0/24'
      gateway: '172.16.1.1'
      iprange: '172.16.1.0/24'
  tags:
    - configuration

- name: Create traefik directory.
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: 0550
  with_items:
    - /etc/traefik
  tags:
    - configuration

- name: Create traefik configuration file.
  template:
    src: "traefik.toml.j2"
    dest: "/etc/traefik/traefik.toml"
    owner: root
    group: docker
    mode: 0550
  notify:
    - restart traefik
  tags:
    - configuration

- name: Create acme file to storing the certificats.
  copy:
    content: ""
    dest: /etc/traefik/acme.json
    force: no
    group: docker
    owner: root
    mode: 0600
  notify:
    - restart traefik
  tags:
    - configuration

- name: Ensure traefik is running.
  docker_container:
    name: webproxy
    image: "{{ traefik_image }}"
    restart_policy: unless-stopped
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/traefik/traefik.toml:/traefik.toml
      - /etc/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/etc/traefik
    capabilities:
      - net_bind_service
    networks:
      - name: "{{ traefik_network }}"
  tags:
    - configuration
